spring:
  profiles:
    active: production

---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: sapassword
    url: jdbc:mysql://localhost:3306/employeedb_pro
    username: root
  jpa:
    hibernate:
      ddl-auto: update

welcome:
  message: 'welcome to production'
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: sapassword
    url: jdbc:mysql://localhost:3306/employeedb_dev
    username: root
  jpa:
    hibernate:
      ddl-auto: update

welcome:
  message: 'welcome to dev'

---

spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: sapassword
    url: jdbc:mysql://localhost:3306/employeedb_qa
    username: root
  jpa:
    hibernate:
      ddl-auto: update

welcome:
  message: 'welcome to qa'

